### ISSUE TITLE
VPN docs

### ISSUE THREAD

**Issue by jason-murray** [markomitranic/.vscode#1]
Hey Marko, thanks so much for your writings on CND and this repo, I'm trying to adopt this now!

My knowledge is falling away a bit at the VPN firewall part so there's a learning opp for me here, and I'd like to help improve the docs if I may.

Some very basic questions:

- Does the openvpn-pihole droplet need a floating IP as well as the workspace droplet?
- Also assuming to apply to firewall to both droplets?

Problem I am facing is once connected to the VPN I cannot ssh to the droplets floating IP.

**Comment by jason-murray** [comment]
I missed a digit off the IP in route-add step 🤦‍♂️

**Comment by markomitranic** [comment]
Hey @Jason-Murray thanks for reaching out! I am sorry about the instructions, they are a work in progress, and were only meant for myself as a reminder :P

The VPN is optional. I installed it only after a bot tried installing a crypto miner into my running postgres instance 🗡️ 
I though of it as a way to elegantly protect the droplet without writing any advanced (and changeable) ufw rules.

**The idea is:** Your mac securely connects to the VPN, only the VPN server can access the VPS. All other traffic to the VPS is simply denied.

- Nah, the VPN droplet is okay to remain flexible. The only purpose of having a floating point IP is to not have to deal with IP change once you rebuild or change your server. When it comes to the VPN droplet, she will give you a hardcoded file that you use to connect, so you never have to worry about its IP at all.
- Nah, only the VPS needs the firewall. The purpose is for it to deny ALL traffic from outside (except the one coming from our VPN). The VPN droplet however does not have to be protected, as it runs no dev services.

Oh, i see your response now :D

**Comment by markomitranic** [comment]
BTW @Jason-Murray heres a pro tip that I didn't yet write down:

You add the floating IP to your local hosts file. I named the domain `workspace`, so that i never have to remember the floating IP again :P

Then another trick - you can edit your local ssh config, so that it uses the workspace name. Also, add the `ForwardAgent` line to it. It will allow your SSH keys to be automagically installed into the VPS, so that your Git works out fo the box in there :) no need for any new keys at all. (this is dangerous to have for other servers, which is why we limit it to workspace only!)

```bash
$ cat ~/.ssh/config 

Host workspace
  HostName workspace
  User root
  ForwardAgent yes
```

I've came upon this approach when i was setting up a YubiKey as my SSH key (I should write that down one day as well hmm) so that my local machine has no ssh keys at all :P

**Comment by jason-murray** [comment]
Amazing, thank you!
